; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:arduino_nano_esp32]
platform = espressif32
board = arduino_nano_esp32
framework = arduino
monitor_speed = 115200
; upload_port = /dev/cu.usbmodem3C8427C2F6D82
; monitor_port = /dev/cu.usbmodem3C8427C2F6D82
lib_deps =
    knolleary/PubSubClient@^2.8
    arduino-libraries/Ethernet@^2.0.2
    vshymanskyy/TinyGSM@^0.12.0
    bblanchon/ArduinoJson@^6.21.5
    4-20ma/ModbusMaster@^2.0.1
    sandeepmistry/LoRa@^0.8.0

[env:arduino_nano_esp32_ota]
extends = env:arduino_nano_esp32
upload_protocol = espota
upload_port = nano-esp32.local
upload_flags =
    --auth=${sysenv.NANO_ESP32_OTA_PASSWORD}
    --port=3232
